###Get all articles
GET http://localhost:4000/articles HTTP/1.1

###Post new article
Post http://localhost:4000/articles HTTP/1.1
Content-Type: application/json

{
    "title": "Fancy new article",
    "body": "OMG it's so fancy I'm gonna die."
}

###Get article by id
GET http://localhost:4000/articles/27 HTTP/1.1

###Patch article (update) by id
PATCH http://localhost:4000/articles/30 HTTP/1.1
Content-Type: application/json

{
    "title": "Fancy new article",
    "content": "New fancy stuff"
}

###Delete Article by od
DELETE http://localhost:4000/articles/27 HTTP/1.1